// 未知错误
public static final int UNKNOWN_ERROR_UPPER_LOGIC_ERROR = 111001;
// 上层参数错误
public static final int UPPER_PARAMETER_ERROR_UPPER_LOGIC_ERROR = 111002;
// 播放器状态错误
public static final int PLAYER_STATUS_ERROR_UPPER_LOGIC_ERROR = 111003;
// 播放器创建失败
public static final int PLAYER_CREATION_FAILED_UPPER_LOGIC_ERROR = 111004;
// 鉴权失败
public static final int AUTHENTICATION_FAILURE_UPPER_LOGIC_ERROR = 111005;
// 手机不支持
public static final int PHONE_DOES_NOT_SUPPORT_UPPER_LOGIC_ERROR = 111006;
// 播放地址为空
public static final int PLAY_ADDRESS_IS_EMPTY_UPPER_LOGIC_ERROR = 111007;
// 自研硬解接口调用失败
public static final int CALL_OF_SELF_GRIND_HARD_SOLUTION_INTERFACE_FAILED_UPPER_LOGIC_ERROR = 111008;
// 下载组件加载失败
public static final int DOWNLOAD_COMPONENT_LOAD_FAILED_UPPER_LOGIC_ERROR = 111009;
// VINFO 解析失败
public static final int VINFO_PARSING_FAILED_UPPER_LOGIC_ERROR = 111010;
// 下载组件startOnlineOrOfflinePlay返回-1
public static final int DOWNLOAD_COMPONENT_STARTONLINEOROFFLINEPLAY_RETURN_1_UPPER_LOGIC_ERROR = 111011;
// 其他错误
public static final int OTHER_MISTAKES_SELF_DEVELOPED_PLAYER = 112000;
// 通用错误
public static final int GENERAL_ERROR_SELF_DEVELOPED_PLAYER = 112001;
// 内存错误
public static final int MEMORY_ERROR_SELF_DEVELOPED_PLAYER = 112002;
// 文件IO错误
public static final int FILE_IO_ERROR_SELF_DEVELOPED_PLAYER = 112003;
// 参数不合法
public static final int ILLEGAL_PARAMETER_SELF_DEVELOPED_PLAYER = 112004;
// 外部主动关闭
public static final int EXTERNAL_ACTIVE_CLOSE_SELF_DEVELOPED_PLAYER = 112005;
// 播放器没准备好
public static final int THE_PLAYER_IS_NOT_READY_SELF_DEVELOPED_PLAYER = 112006;
// 网络错误
public static final int NETWORK_ERROR_SELF_DEVELOPED_PLAYER = 112007;
// 数据格式错误
public static final int DATA_IN_WRONG_FORMAT_SELF_DEVELOPED_PLAYER = 112008;
// 缓冲超时
public static final int BUFFER_TIMEOUT_SELF_DEVELOPED_PLAYER = 112009;
// 试看超时
public static final int TRY_OVERTIME_SELF_DEVELOPED_PLAYER = 112010;
// 格式不支持
public static final int FORMAT_NOT_SUPPORTED_SELF_DEVELOPED_PLAYER = 112011;
// TCP接收失败
public static final int TCP_RECEIVE_FAILED_SELF_DEVELOPED_PLAYER = 112012;
// 解码器注册失败
public static final int DECODER_REGISTRATION_FAILED_SELF_DEVELOPED_PLAYER = 112013;
// socket获取本地地址失败
public static final int SOCKET_FAILED_TO_GET_LOCAL_ADDRESS_SELF_DEVELOPED_PLAYER = 112021;
// socket打开失败
public static final int SOCKET_OPEN_FAILED_SELF_DEVELOPED_PLAYER = 112022;
// bind失败
public static final int BIND_FAILURE_SELF_DEVELOPED_PLAYER = 112023;
// listener失败
public static final int LISTENER_FAILED_SELF_DEVELOPED_PLAYER = 112024;
// Poll失败
public static final int POLL_FAILURE_SELF_DEVELOPED_PLAYER = 112025;
// accept 失败
public static final int ACCEPT_FAILED_SELF_DEVELOPED_PLAYER = 112026;
// Recv失败
public static final int RECV_FAILURE_SELF_DEVELOPED_PLAYER = 112027;
// read超时
public static final int READ_TIMEOUT_SELF_DEVELOPED_PLAYER = 112028;
// send失败
public static final int SEND_FAILURE_SELF_DEVELOPED_PLAYER = 112029;
// write超时
public static final int WRITE_TIMEOUT_SELF_DEVELOPED_PLAYER = 112030;
// open超时
public static final int OPEN_TIMEOUT_SELF_DEVELOPED_PLAYER = 112031;
// socket相关的其他错误
public static final int OTHER_SOCKET_RELATED_ERRORS_SELF_DEVELOPED_PLAYER = 112032;
// IO错误
public static final int IO_ERROR_SELF_DEVELOPED_PLAYER = 112041;
// 数据不合法
public static final int ILLEGAL_DATA_SELF_DEVELOPED_PLAYER = 112042;
// 没找到解码器
public static final int NO_DECODER_FOUND_SELF_DEVELOPED_PLAYER = 112043;
// 没找到对应demuxer
public static final int NO_CORRESPONDING_DEMUXER_FOUND_SELF_DEVELOPED_PLAYER = 112044;
// 外部退出
public static final int EXTERNAL_EXIT_SELF_DEVELOPED_PLAYER = 112045;
// 第三方库错误
public static final int THIRD_PARTY_LIBRARY_ERROR_SELF_DEVELOPED_PLAYER = 112046;
// 没找到对应filter
public static final int NO_CORRESPONDING_FILTER_FOUND_SELF_DEVELOPED_PLAYER = 112047;
// 解码参数设置失败
public static final int DECODING_PARAMETER_SETTING_FAILED_SELF_DEVELOPED_PLAYER = 112048;
// 没找到对应协议
public static final int NO_CORRESPONDING_AGREEMENT_FOUND_SELF_DEVELOPED_PLAYER = 112049;
// 没找到对应流格式
public static final int NO_CORRESPONDING_STREAM_FORMAT_FOUND_SELF_DEVELOPED_PLAYER = 112050;
// 未知错误
public static final int UNKNOWN_ERROR_SELF_DEVELOPED_PLAYER = 112051;
// 链接超时
public static final int LINK_TIMEOUT_SELF_DEVELOPED_PLAYER = 112052;
// 没找到对应解码器上下文
public static final int NO_CORRESPONDING_DECODER_CONTEXT_FOUND_SELF_DEVELOPED_PLAYER = 112053;
// video decoder 没找到
public static final int VIDEO_DECODER_NOT_FOUND_SELF_DEVELOPED_PLAYER = 112062;
// video decoder 解码失败
public static final int VIDEO_DECODER_DECODING_FAILED_SELF_DEVELOPED_PLAYER = 112063;
// video pts 错误
public static final int VIDEO_PTS_ERROR_SELF_DEVELOPED_PLAYER = 112064;
// audio decoder 没找到
public static final int AUDIO_DECODER_NOT_FOUND_SELF_DEVELOPED_PLAYER = 112082;
// audio decoder 解码失败
public static final int AUDIO_DECODER_DECODING_FAILED_SELF_DEVELOPED_PLAYER = 112083;
// audio pts 错误
public static final int AUDIO_PTS_ERROR_SELF_DEVELOPED_PLAYER = 112084;
// 数据流错误Player_base_err_selfplayer_avsrc_error
public static final int DATA_FLOW_ERROR_PLAYER_BASE_ERROR_SELFPLAYER_AVSRC_ERROR_SELF_DEVELOPED_PLAYER = 112101;
// 设置解码器失败Player_base_err_selfplayer_set_dec_failed
public static final int FAILED_TO_SET_DECODER_PLAYER_BASE_ERR_SELFPLAYER_SET_DEC_FAILED_SELF_DEVELOPED_PLAYER = 112105;
// 解码失败Player_base_err_selfplayer_decider_failed
public static final int DECODING_FAILED_PLAYER_BASE_ERR_SELFPLAYER_DECISION_FAILED_SELF_DEVELOPED_PLAYER = 112106;
// dolby解码失败Player_base_err_selfplayer_dolby_failed
public static final int DOLBY_DECODING_FAILED_PLAYER_BASE_ERR_SELFPLAYER_DOLBY_FAILED_SELF_DEVELOPED_PLAYER = 112108;
// hevc解码失败Player_base_err_selfplayer_hevc_failed
public static final int HEVC_DECODING_FAILED_PLAYER_BASE_ERR_SELFPLAYER_HEVC_FAILED_SELF_DEVELOPED_PLAYER = 112109;
// URL有问题Player_base_err_selfplayer_url_error
public static final int PLAYER_BASE_ERR_SELFPLAYER_URL_ERROR_SELF_DEVELOPED_PLAYER = 112111;
// 打开失败Player_base_err_selfplayer_open_failed
public static final int FAILED_TO_OPEN_PLAYER_BASE_ERR_SELFPLAYER_OPEN_FAILED_SELF_DEVELOPED_PLAYER = 112112;
// start函数异常Player_base_err_selfplayer_start_exce
public static final int START_FUNCTION_EXCEPTION_PLAYER_BASE_ERR_SELFPLAYER_START_EXCE_SELF_DEVELOPED_PLAYER = 112113;
// 网络问题Player_base_err_selfplayer_network_err
public static final int PLAYER_BASE_ERR_SELFPLAYER_NETWORK_ERR_SELF_DEVELOPED_PLAYER = 112141;
// 超时Player_base_err_selfplayer_timeout
public static final int TIMEOUT_PLAYER_BASE_ERR_SELFPLAYER_TIMEOUT_SELF_DEVELOPED_PLAYER = 112142;
// 系统播放器未知错误
public static final int SYSTEM_PLAYER_UNKNOWN_ERROR_SYSTEM_PLAYER = 113000;
// 内部超时，prepare超时25秒
public static final int INTERNAL_TIMEOUT_PREPARE_TIMEOUT_25_SECONDS_SYSTEM_PLAYER = 113001;
// 数据超时，取数据10秒超时
public static final int DATA_TIMEOUT_TAKE_DATA_FOR_10_SECONDS_TIMEOUT_SYSTEM_PLAYER = 113002;
// 播放状态非法
public static final int ILLEGAL_PLAY_STATUS_SYSTEM_PLAYER = 113003;
// 播放参数非法
public static final int ILLEGAL_PLAYBACK_PARAMETERS_SYSTEM_PLAYER = 113004;
// 文件IO错误
public static final int FILE_IO_ERROR_SYSTEM_PLAYER = 113005;
// 编码格式不规范
public static final int THE_CODING_FORMAT_IS_NOT_STANDARD_SYSTEM_PLAYER = 113006;
// 格式不支持
public static final int FORMAT_NOT_SUPPORTED_SYSTEM_PLAYER = 113007;
// 当前视频流不支持循环播放
public static final int THE_CURRENT_VIDEO_STREAM_DOES_NOT_SUPPORT_LOOPING_SYSTEM_PLAYER = 113008;
// 12秒内播放进度没变化
public static final int NO_CHANGE_IN_PLAYBACK_PROGRESS_IN_12_SECONDS_SYSTEM_PLAYER = 113009;
// mediaserver进程错误
public static final int MEDIASERVER_PROCESS_ERROR_SYSTEM_PLAYER = 113010;
// open通用错误
public static final int OPEN_COMMON_ERROR_SYSTEM_PLAYER = 113011;
// 系统缓冲超时
public static final int SYSTEM_BUFFER_TIMEOUT_SYSTEM_PLAYER = 113012;
// 网络错误
public static final int NETWORK_ERROR_SYSTEM_PLAYER = 113013;
// 网络层未知错误
public static final int NETWORK_LAYER_UNKNOWN_ERROR_SYSTEM_PLAYER = 1401001;
// 无法解析该域名-UnknowHostException
public static final int THE_DOMAIN_NAME_COULD_NOT_BE_RESOLVED_UNKNOWHOSTEXCEPTION_SYSTEM_PLAYER = 1401002;
// 连接出错-ConnectException
public static final int CONNECTION_ERROR_CONNECTEXCEPTION_SYSTEM_PLAYER = 1401003;
// 请求超时-ConnectTimeoutException
public static final int REQUEST_TIMEOUT_CONNECTTIMEOUTEXCEPTION_SYSTEM_PLAYER = 1401004;
// 服务器响应超时-SocketTimeoutException
public static final int SERVER_RESPONSE_TIMEOUT_SOCKETIMEOUTEXCEPTION_SYSTEM_PLAYER = 1401005;
// IO异常-IOException
public static final int IO_EXCEPTION_IOEXCEPTION_SYSTEM_PLAYER = 1401006;
// 参数异常-IllegalValueException
public static final int PARAMETER_EXCEPTION_ILLEGALVALUEEXCEPTION_SYSTEM_PLAYER = 1401007;
// 文件找不到异常-FileNotFoundException
public static final int FILE_CANNOT_FIND_EXCEPTION_FILENOTFOUNDEXCEPTION_SYSTEM_PLAYER = 1401008;
// 协议错误-CllientProtocolException
public static final int PROTOCOL_ERROR_CLLIENTPROTOCOLEXCEPTION_SYSTEM_PLAYER = 1401009;
// 循环重定向-CircularRedirectException
public static final int CIRCULAR_REDIRECTION_CIRCULAR_REDIRECTEXCEPTION_SYSTEM_PLAYER = 1401010;
// 服务器无响应-NoHttpResponseException
public static final int NO_RESPONSE_FROM_SERVER_NOHTTPRESPONSEEXCEPTION_SYSTEM_PLAYER = 1401011;
// 返回http对应状态码
public static final int RETURN_HTTP_CORRESPONDING_STATUS_CODE_SYSTEM_PLAYER = 1401012;
// http返回信息不是xml
public static final int HTTP_RETURN_INFORMATION_IS_NOT_XML_SYSTEM_PLAYER = 1401013;
// cgi返回s != '0'
public static final int CGI_RETURNS_S_0_SYSTEM_PLAYER = 1401014;
// xml解析失败
public static final int XML_PARSING_FAILED_SYSTEM_PLAYER = 1401015;
// https异常-SSLException
public static final int HTTPS_EXCEPTION_SSLEXCEPTION_SYSTEM_PLAYER = 1401016;
// https异常-HandShakeException
public static final int HTTPS_EXCEPTION_HANDSHAKEEXCEPTION_SYSTEM_PLAYER = 1401017;
// https异常-KeyException
public static final int HTTPS_EXCEPTION_KEYEXCEPTION_SYSTEM_PLAYER = 1401018;
// https异常-PeerUnverifiedException
public static final int HTTPS_EXCEPTION_PEERUNVERIFIEDEXCEPTION_SYSTEM_PLAYER = 1401019;
// https异常-ProtocolException
public static final int HTTPS_EXCEPTION_PROTOCOLEXCEPTION_SYSTEM_PLAYER = 1401020;
// socket错误-SocketException
public static final int SOCKET_ERROR_SOCKETEXCEPTION_SYSTEM_PLAYER = 1401021;
// http状态码-101
public static final int HTTP_STATUS_CODE_101_SYSTEM_PLAYER = 1401101;
// http状态码-200
public static final int HTTP_STATUS_CODE_200_SYSTEM_PLAYER = 1401200;
// http状态码-307
public static final int HTTP_STATUS_CODE_307_SYSTEM_PLAYER = 1401307;
// http状态码-400
public static final int HTTP_STATUS_CODE_400_SYSTEM_PLAYER = 1401400;
// http状态码-401
public static final int HTTP_STATUS_CODE_401_SYSTEM_PLAYER = 1401401;
// http状态码-402
public static final int HTTP_STATUS_CODE_402_SYSTEM_PLAYER = 1401402;
// http状态码-403
public static final int HTTP_STATUS_CODE_403_SYSTEM_PLAYER = 1401403;
// http状态码-404
public static final int HTTP_STATUS_CODE_404_SYSTEM_PLAYER = 1401404;
// http状态码-405
public static final int HTTP_STATUS_CODE_405_SYSTEM_PLAYER = 1401405;
// http状态码-500
public static final int HTTP_STATUS_CODE_500_SYSTEM_PLAYER = 1401500;
// http状态码-501
public static final int HTTP_STATUS_CODE_501_SYSTEM_PLAYER = 1401501;
// http状态码-502
public static final int HTTP_STATUS_CODE_502_SYSTEM_PLAYER = 1401502;
// http状态码-503
public static final int HTTP_STATUS_CODE_503_SYSTEM_PLAYER = 1401503;
// http状态码-504
public static final int HTTP_STATUS_CODE_504_SYSTEM_PLAYER = 1401504;
// http状态码-505
public static final int HTTP_STATUS_CODE_505_SYSTEM_PLAYER = 1401505;
// 离线下载没有找到指定的format
public static final int THE_SPECIFIED_FORMAT_WAS_NOT_FOUND_FOR_OFFLINE_DOWNLOAD_GETVINFO_RETURN_FORMAT_PROBLEM = 1200001;
// 离线下载getVinfo解析失败
public static final int OFFLINE_DOWNLOAD_GETVINFO_PARSING_FAILED_GETVINFO_RETURN_FORMAT_PROBLEM = 1200002;
// 离线下载vinfo里面的url为空
public static final int THE_URL_IN_THE_OFFLINE_DOWNLOAD_VINFO_IS_EMPTY_GETVINFO_RETURN_FORMAT_PROBLEM = 1200004;
// 离线下载请求drm视频，返回非drm视频，将重新请求非drm视频下载
public static final int OFFLINE_DOWNLOAD_REQUEST_DRM_VIDEO_RETURN_NON_DRM_VIDEO_WILL_RE_REQUEST_NON_DRM_VIDEO_DOWNLOAD_GETVINFO_RETURN_FORMAT_PROBLEM = 1200005;
// 离线下载请求drm视频，返getVinfo解析失败
public static final int OFFLINE_DOWNLOAD_REQUEST_DRM_VIDEO_GETVINFO_PARSING_FAILED_GETVINFO_RETURN_FORMAT_PROBLEM = 1200006;
// 离线下载没有合法的下载类型
public static final int OFFLINE_DOWNLOAD_DOES_NOT_HAVE_A_LEGAL_DOWNLOAD_TYPE_GETVINFO_RETURN_FORMAT_PROBLEM = 1200007;
// 离线下载，后台返回加密视频，但是key为空
public static final int OFFLINE_DOWNLOAD_ENCRYPTED_VIDEO_IS_RETURNED_IN_THE_BACKGROUND_BUT_THE_KEY_IS_EMPTY_GETVINFO_RETURN_FORMAT_PROBLEM = 1200008;
// getVinfo解析失败
public static final int GETVINFO_PARSING_FAILED_GETVINFO_RETURN_FORMAT_PROBLEM = 1200009;
// 没有找到format
public static final int FORMAT_NOT_FOUND_GETVINFO_RETURN_FORMAT_PROBLEM = 1200011;
// vinfo中url为空
public static final int URL_IN_VINFO_IS_EMPTY_GETVINFO_RETURN_FORMAT_PROBLEM = 1200012;
// CGI参数错误或者向服务器发包错误
public static final int CGI_PARAMETER_ERROR_OR_ERROR_SENDING_TO_SERVER_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300001;
// CGI从服务器接包错误
public static final int CGI_RECEIVE_PACKAGE_ERROR_FROM_SERVER_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300002;
// CGI从服务器解包错误
public static final int CGI_UNPACKING_FROM_SERVER_ERROR_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300003;
// CGI连接服务器网络错误
public static final int CGI_CONNECTION_SERVER_NETWORK_ERROR_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300004;
// CGI连接超时
public static final int CGI_CONNECTION_TIMEOUT_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300006;
// CGI访问服务未知错误
public static final int CGI_ACCESS_SERVICE_UNKNOWN_ERROR_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300007;
// CGI系统错误
public static final int CGI_SYSTEM_ERROR_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300050;
// vid个数超出范围
public static final int NUMBER_OF_VIDS_OUT_OF_RANGE_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300051;
// CGI访问服务失败
public static final int CGI_ACCESS_SERVICE_FAILED_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300052;
// vid不合法（video超时）
public static final int ILLEGAL_VIDEO_VIDEO_TIMEOUT_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300061;
// 视频状态不合法
public static final int ILLEGAL_VIDEO_STATUS_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300062;
// 清晰度格式不合法
public static final int ILLEGAL_DEFINITION_FORMAT_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300063;
// 付费服务spp_tpay出错
public static final int ERROR_IN_PAY_SERVICE_SPP_TPAY_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300064;
// 速度格式不合法
public static final int ILLEGAL_SPEED_FORMAT_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300065;
// 文件名不合法
public static final int ILLEGAL_FILE_NAME_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300066;
// 视频格式不存在
public static final int VIDEO_FORMAT_DOES_NOT_EXIST_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300067;
// 文件状态不合法
public static final int ILLEGAL_FILE_STATUS_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300068;
// format列表为空
public static final int FORMAT_LIST_IS_EMPTY_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300069;
// 构造key失败
public static final int FAILED_TO_CONSTRUCT_KEY_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300070;
// 未找到HLS CDN或者构造sha失败
public static final int HLS_CDN_NOT_FOUND_OR_FAILED_TO_CONSTRUCT_SHA_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300071;
// 不支持HLS
public static final int NO_SUPPORT_FOR_HLS_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300072;
// 生成文件名失败
public static final int FAILED_TO_GENERATE_FILENAME_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300073;
// 分片号不合法
public static final int ILLEGAL_PARTITION_NUMBER_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300074;
// 构造文件失败
public static final int FAILED_TO_CONSTRUCT_FILE_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300075;
// 获取m3u8文件名失败
public static final int FAILED_TO_GET_M3U8_FILENAME_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300076;
// 生成HLS key 失败
public static final int FAILED_TO_GENERATE_HLS_KEY_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300077;
// 非正版腾讯视频app
public static final int NON_GENUINE_TENCENT_VIDEO_APP_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300079;
// 版权限制
public static final int COPYRIGHT_RESTRICTIONS_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300080;
// referer限制
public static final int REFERER_RESTRICTIONS_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300081;
// qzone权限限制
public static final int QZONE_PERMISSION_RESTRICTIONS_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300082;
// 付费限制
public static final int PAYMENT_RESTRICTION_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300083;
// 访问ip是黑名单
public static final int ACCESS_IP_IS_BLACKLIST_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300084;
// CGI访问key不正确
public static final int CGI_ACCESS_KEY_INCORRECT_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300085;
// CGI访问频率险资和
public static final int CGI_ACCESS_FREQUENCY_INSURANCE_AND_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300086;
// 帐号登录设备过多
public static final int TOO_MANY_ACCOUNT_LOGIN_DEVICES_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300094;
// QQOpenError
public static final int QQOPENERROR_GETVINFO_RETURNS_BACKGROUND_ERROR_CODE = 1300401;
// 网络层未知错误
public static final int NETWORK_LAYER_UNKNOWN_ERROR_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402001;
// 无法解析该域名-UnknowHostException
public static final int THE_DOMAIN_NAME_COULD_NOT_BE_RESOLVED_UNKNOWHOSTEXCEPTION_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402002;
// 连接出错-ConnectException
public static final int CONNECTION_ERROR_CONNECTEXCEPTION_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402003;
// 请求超时-ConnectTimeoutException
public static final int REQUEST_TIMEOUT_CONNECTTIMEOUTEXCEPTION_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402004;
// 服务器响应超时-SocketTimeoutException
public static final int SERVER_RESPONSE_TIMEOUT_SOCKETIMEOUTEXCEPTION_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402005;
// IO异常-IOException
public static final int IO_EXCEPTION_IOEXCEPTION_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402006;
// 参数异常-IllegalValueException
public static final int PARAMETER_EXCEPTION_ILLEGALVALUEEXCEPTION_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402007;
// 文件找不到异常-FileNotFoundException
public static final int FILE_CANNOT_FIND_EXCEPTION_FILENOTFOUNDEXCEPTION_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402008;
// 协议错误-CllientProtocolException
public static final int PROTOCOL_ERROR_CLLIENTPROTOCOLEXCEPTION_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402009;
// 循环重定向-CircularRedirectException
public static final int CIRCULAR_REDIRECTION_CIRCULAR_REDIRECTEXCEPTION_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402010;
// 服务器无响应-NoHttpResponseException
public static final int NO_RESPONSE_FROM_SERVER_NOHTTPRESPONSEEXCEPTION_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402011;
// 返回http对应状态码
public static final int RETURN_HTTP_CORRESPONDING_STATUS_CODE_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402012;
// http返回信息不是xml
public static final int HTTP_RETURN_INFORMATION_IS_NOT_XML_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402013;
// cgi返回s != '0'
public static final int CGI_RETURNS_S_0_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402014;
// xml解析失败
public static final int XML_PARSING_FAILED_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402015;
// https异常-SSLException
public static final int HTTPS_EXCEPTION_SSLEXCEPTION_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402016;
// https异常-HandShakeException
public static final int HTTPS_EXCEPTION_HANDSHAKEEXCEPTION_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402017;
// https异常-KeyException
public static final int HTTPS_EXCEPTION_KEYEXCEPTION_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402018;
// https异常-PeerUnverifiedException
public static final int HTTPS_EXCEPTION_PEERUNVERIFIEDEXCEPTION_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402019;
// https异常-ProtocolException
public static final int HTTPS_EXCEPTION_PROTOCOLEXCEPTION_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402020;
// socket错误-SocketException
public static final int SOCKET_ERROR_SOCKETEXCEPTION_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402021;
// http状态码-101
public static final int HTTP_STATUS_CODE_101_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402101;
// http状态码-200
public static final int HTTP_STATUS_CODE_200_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402200;
// http状态码-307
public static final int HTTP_STATUS_CODE_307_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402307;
// http状态码-400
public static final int HTTP_STATUS_CODE_400_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402400;
// http状态码-401
public static final int HTTP_STATUS_CODE_401_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402401;
// http状态码-402
public static final int HTTP_STATUS_CODE_402_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402402;
// http状态码-403
public static final int HTTP_STATUS_CODE_403_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402403;
// http状态码-404
public static final int HTTP_STATUS_CODE_404_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402404;
// http状态码-405
public static final int HTTP_STATUS_CODE_405_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402405;
// http状态码-500
public static final int HTTP_STATUS_CODE_500_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402500;
// http状态码-501
public static final int HTTP_STATUS_CODE_501_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402501;
// http状态码-502
public static final int HTTP_STATUS_CODE_502_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402502;
// http状态码-503
public static final int HTTP_STATUS_CODE_503_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402503;
// http状态码-504
public static final int HTTP_STATUS_CODE_504_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402504;
// http状态码-505
public static final int HTTP_STATUS_CODE_505_GETVKEY_GETVBKEY_NETWORK_ERROR = 1402505;
// 离线下载getVkey解析失败
public static final int FAILED_TO_DOWNLOAD_GETVKEY_OFFLINE_RETURN_FORMAT_OF_GETVKEY_GETVBKEY = 1200003;
// 在线播放getVkey解析失败
public static final int ONLINE_PLAY_GETVKEY_PARSING_FAILED_RETURN_FORMAT_OF_GETVKEY_GETVBKEY = 1200010;
// cgi参数错误/cgi向服务器发包错误
public static final int CGI_PARAMETER_ERROR_CGI_CONTRACT_ERROR_TO_SERVER_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300201;
// cgi从服务器接包错误
public static final int CGI_RECEIVE_PACKAGE_ERROR_FROM_SERVER_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300202;
// cgi从服务器解包错误
public static final int CGI_UNPACKING_FROM_SERVER_ERROR_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300203;
// cgi连接服务器网络错误
public static final int CGI_CONNECTION_SERVER_NETWORK_ERROR_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300204;
// cgi连接服务超时
public static final int CGI_CONNECTION_SERVICE_TIMEOUT_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300206;
// cgi访问服务未知错误
public static final int CGI_ACCESS_SERVICE_UNKNOWN_ERROR_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300207;
// cgi系统错误
public static final int CGI_SYSTEM_ERROR_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300250;
// vid个数超出范围
public static final int NUMBER_OF_VIDS_OUT_OF_RANGE_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300251;
// cgi访问服务失败
public static final int CGI_ACCESS_SERVICE_FAILED_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300252;
// 传入参数vid,format和filename不匹配 vid不合法（video超时）
public static final int THE_INPUT_PARAMETER_VID_FORMAT_AND_FILENAME_DO_NOT_MATCH_ILLEGAL_VIDEO_VIDEO_TIMEOUT_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300260;
// vid不合法（video超时）
public static final int ILLEGAL_VIDEO_VIDEO_TIMEOUT_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300261;
// 视频状态不合法
public static final int ILLEGAL_VIDEO_STATUS_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300262;
// 清晰度格式不合法
public static final int ILLEGAL_DEFINITION_FORMAT_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300263;
// 付费服务出错
public static final int ERROR_IN_PAID_SERVICE_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300264;
// 速度格式不合法
public static final int ILLEGAL_SPEED_FORMAT_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300265;
// 文件名不合法
public static final int ILLEGAL_FILE_NAME_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300266;
// format不合法
public static final int ILLEGAL_FORMAT_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300267;
// 文件状态不合法
public static final int ILLEGAL_FILE_STATUS_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300268;
// format列表为空
public static final int FORMAT_LIST_IS_EMPTY_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300269;
// 构造key失败
public static final int FAILED_TO_CONSTRUCT_KEY_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300270;
// 构造sha失败
public static final int FAILED_TO_CONSTRUCT_SHA_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300271;
// 不支持HLS
public static final int NO_SUPPORT_FOR_HLS_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300272;
// 生成filename失败了
public static final int FAILED_TO_GENERATE_FILENAME_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300273;
// idx超出范围
public static final int IDX_OUT_OF_RANGE_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300274;
// 构造文件失败
public static final int FAILED_TO_CONSTRUCT_FILE_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300275;
// 获取m3u8文件名失败
public static final int FAILED_TO_GET_M3U8_FILENAME_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300276;
// 生成hls key失败
public static final int FAILED_TO_GENERATE_HLS_KEY_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300277;
// 非正版腾讯视频app
public static final int NON_GENUINE_TENCENT_VIDEO_APP_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300279;
// 版权限制
public static final int COPYRIGHT_RESTRICTIONS_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300280;
// referer限制
public static final int REFERER_RESTRICTIONS_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300281;
// qzone权限限制
public static final int QZONE_PERMISSION_RESTRICTIONS_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300282;
// 付费限制
public static final int PAYMENT_RESTRICTION_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300283;
// 访问ip是黑名单
public static final int ACCESS_IP_IS_BLACKLIST_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300284;
// CGI访问key不正确
public static final int CGI_ACCESS_KEY_INCORRECT_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300285;
// CGI访问频率险资和
public static final int CGI_ACCESS_FREQUENCY_INSURANCE_AND_GETVKEY_GETVBKEY_RETURN_BACKGROUND_ERROR_CODE = 1300286;
// 输入参数非法
public static final int ILLEGAL_INPUT_PARAMETER_LIVEINFO_NETWORK_LAYER_ERROR = 143004;
// CGI错误
public static final int CGI_ERROR_LIVEINFO_NETWORK_LAYER_ERROR = 141006;
// 未知错误
public static final int UNKNOWN_ERROR_LIVEINFO_NETWORK_LAYER_ERROR = 144000;
// 网络错误
public static final int NETWORK_ERROR_LIVEINFO_NETWORK_LAYER_ERROR = 141001;
// 返回的info不对
public static final int INCORRECT_INFO_RETURNED_LIVEINFO_NETWORK_LAYER_ERROR = 141007;
// json解析错误
public static final int JSON_PARSING_ERROR_PARSING_ERROR = 121008;
// 查不到频道id
public static final int CHANNEL_ID_NOT_FOUND_LIVEINFO_BACKGROUND_RETURN = 130001;
// 非重点区域限制观看
public static final int RESTRICTED_VIEWING_IN_NON_KEY_AREAS_LIVEINFO_BACKGROUND_RETURN = 130002;
// 带宽达到一定比例，限制非重点区域观看
public static final int BANDWIDTH_REACHES_A_CERTAIN_PROPORTION_LIMITING_VIEWING_IN_NON_KEY_AREAS_LIVEINFO_BACKGROUND_RETURN = 130003;
// 带宽整体已满，限制观看
public static final int BANDWIDTH_IS_FULL_AS_A_WHOLE_LIMIT_VIEWING_LIVEINFO_BACKGROUND_RETURN = 130004;
// 所在地区无播放版权
public static final int NO_BROADCASTING_COPYRIGHT_IN_THE_REGION_LIVEINFO_BACKGROUND_RETURN = 130005;
// 频道信号中断
public static final int CHANNEL_SIGNAL_INTERRUPT_LIVEINFO_BACKGROUND_RETURN = 130006;
// 节目未开始
public static final int PROGRAM_NOT_STARTED_LIVEINFO_BACKGROUND_RETURN = 130007;
// 节目已结束
public static final int PROGRAM_ENDED_LIVEINFO_BACKGROUND_RETURN = 130008;
// 当前频道达到人数上限
public static final int THE_CURRENT_CHANNEL_HAS_REACHED_THE_MAXIMUM_NUMBER_OF_PEOPLE_LIVEINFO_BACKGROUND_RETURN = 130009;
// 强制新直播
public static final int FORCE_NEW_LIVE_LIVEINFO_BACKGROUND_RETURN = 130010;
// 强制控件P2P
public static final int FORCE_CONTROL_P2P_LIVEINFO_BACKGROUND_RETURN = 130011;
// 节目当前时段无版权
public static final int NO_COPYRIGHT_IN_THE_CURRENT_PERIOD_OF_THE_PROGRAM_LIVEINFO_BACKGROUND_RETURN = 130012;
// 仅PC（win平台）加载控件，用P2P播放
public static final int ONLY_PC_WIN_PLATFORM_LOADS_CONTROL_AND_PLAYS_IT_WITH_P2P_LIVEINFO_BACKGROUND_RETURN = 130013;
// 携带参数格式出错
public static final int ERROR_IN_CARRYING_PARAMETER_FORMAT_LIVEINFO_BACKGROUND_RETURN = 130014;
// 请求的视频流类型未知
public static final int UNKNOWN_VIDEO_STREAM_TYPE_REQUESTED_LIVEINFO_BACKGROUND_RETURN = 130015;
// （内部直播用）仅公司内部直播
public static final int FOR_INTERNAL_LIVE_BROADCAST_ONLY_FOR_INTERNAL_LIVE_BROADCAST_OF_THE_COMPANY_LIVEINFO_BACKGROUND_RETURN = 130016;
// PC web 无效 referer
public static final int PC_WEB_INVALID_REFERER_LIVEINFO_BACKGROUND_RETURN = 130017;
// 仅公司内部直播，用户不在白名单
public static final int ONLY_INTERNAL_LIVE_BROADCAST_OF_THE_COMPANY_USERS_ARE_NOT_ON_THE_WHITE_LIST_LIVEINFO_BACKGROUND_RETURN = 130018;
// 未知app来源
public static final int UNKNOWN_APP_SOURCE_LIVEINFO_BACKGROUND_RETURN = 130019;
// （flash用）flash播放器，来源页面不在白名单内
public static final int FOR_FLASH_FLASH_PLAYER_THE_SOURCE_PAGE_IS_NOT_IN_THE_WHITE_LIST_LIVEINFO_BACKGROUND_RETURN = 130020;
// 无效的命令字
public static final int INVALID_COMMAND_WORD_LIVEINFO_BACKGROUND_RETURN = 130021;
// 教育直播专用，验权失败
public static final int EXCLUSIVE_USE_OF_LIVE_EDUCATION_FAILED_TO_VERIFY_THE_RIGHT_LIVEINFO_BACKGROUND_RETURN = 130022;
// 请求付费鉴权模块失败（网络超时或解析出错）
public static final int FAILED_TO_REQUEST_PAYMENT_AUTHENTICATION_MODULE_NETWORK_TIMEOUT_OR_RESOLUTION_ERROR_LIVEINFO_BACKGROUND_RETURN = 130023;
// sng权限验证超时
public static final int SNG_PERMISSION_VERIFICATION_TIMEOUT_LIVEINFO_BACKGROUND_RETURN = 130024;
// 无用户登录信息（登陆态cookie缺少必填字段）
public static final int NO_USER_LOGIN_INFORMATION_THE_LOGIN_COOKIE_LACKS_REQUIRED_FIELDS_LIVEINFO_BACKGROUND_RETURN = 130025;
// vip验证超时
public static final int VIP_VERIFICATION_TIMEOUT_LIVEINFO_BACKGROUND_RETURN = 130026;
// ptlogin验证超时
public static final int PTLOGIN_VERIFICATION_TIMEOUT_LIVEINFO_BACKGROUND_RETURN = 130027;
// ptlogin验证失败
public static final int PTLOGIN_VALIDATION_FAILED_LIVEINFO_BACKGROUND_RETURN = 130028;
// l5出错，登录验证失败
public static final int L5_ERROR_LOGIN_VERIFICATION_FAILED_LIVEINFO_BACKGROUND_RETURN = 130029;
// 当前节目未付清
public static final int CURRENT_PROGRAM_OUTSTANDING_LIVEINFO_BACKGROUND_RETURN = 130030;
// qq登录验证失败
public static final int QQ_LOGIN_VERIFICATION_FAILED_LIVEINFO_BACKGROUND_RETURN = 130031;
// CKEY验证失败
public static final int CKEY_VERIFICATION_FAILED_LIVEINFO_BACKGROUND_RETURN = 130032;
// 付费验证请求重试超时
public static final int PAYMENT_VERIFICATION_REQUEST_RETRY_TIMEOUT_LIVEINFO_BACKGROUND_RETURN = 130033;
// 付费验证请求未带uin字段
public static final int PAYMENT_VERIFICATION_REQUEST_WITHOUT_UIN_FIELD_LIVEINFO_BACKGROUND_RETURN = 130034;
// 付费验证结果解析错误
public static final int PAYMENT_VERIFICATION_RESULT_PARSING_ERROR_LIVEINFO_BACKGROUND_RETURN = 130035;
// ptlogin验证重试超时
public static final int PTLOGIN_AUTHENTICATION_RETRY_TIMEOUT_LIVEINFO_BACKGROUND_RETURN = 130036;
// ptlongin验证初始化请求失败
public static final int PTLONGIN_FAILED_TO_VERIFY_INITIALIZATION_REQUEST_LIVEINFO_BACKGROUND_RETURN = 130037;
// ptlogin验证结果解析错误，登录验证失败
public static final int PTLOGIN_VALIDATION_RESULT_PARSING_ERROR_LOGIN_VALIDATION_FAILED_LIVEINFO_BACKGROUND_RETURN = 130038;
// 非法头部长度
public static final int ILLEGAL_HEAD_LENGTH_LIVEINFO_BACKGROUND_RETURN = 130039;
// 名字服务出错
public static final int NAME_SERVICE_ERROR_LIVEINFO_BACKGROUND_RETURN = 130040;
// protobuf序列化出错
public static final int PROTOBUF_SERIALIZATION_ERROR_LIVEINFO_BACKGROUND_RETURN = 130041;
// 乌托邦权限验证失败
public static final int UTOPIA_AUTHORITY_VERIFICATION_FAILED_LIVEINFO_BACKGROUND_RETURN = 130042;
// 未登录乌托邦系统
public static final int NOT_LOGGED_INTO_THE_UTOPIAN_SYSTEM_LIVEINFO_BACKGROUND_RETURN = 130043;
// 乌托邦验证超时，内部系统验证失败
public static final int UTOPIA_VERIFICATION_TIMEOUT_INTERNAL_SYSTEM_VERIFICATION_FAILED_LIVEINFO_BACKGROUND_RETURN = 130044;
// 试看次数达到上限
public static final int THE_NUMBER_OF_TRIALS_REACHED_THE_UPPER_LIMIT_LIVEINFO_BACKGROUND_RETURN = 130045;
// 试看技术鉴权失败
public static final int TRY_TO_SEE_THE_FAILURE_OF_TECHNOLOGY_AUTHENTICATION_LIVEINFO_BACKGROUND_RETURN = 130046;
// 试看计数失败，无法试看
public static final int TRY_COUNT_FAILED_UNABLE_TO_TRY_LIVEINFO_BACKGROUND_RETURN = 130047;
// 微信登录验证失败
public static final int WECHAT_LOGIN_VERIFICATION_FAILED_LIVEINFO_BACKGROUND_RETURN = 130048;
// 微信登录验证超时
public static final int WECHAT_LOGIN_VERIFICATION_TIMEOUT_LIVEINFO_BACKGROUND_RETURN = 130049;
// 微信内部票据验证超时
public static final int WECHAT_INTERNAL_BILL_VERIFICATION_TIMEOUT_LIVEINFO_BACKGROUND_RETURN = 130050;
// 当前没有正在直播的节目
public static final int THERE_ARE_CURRENTLY_NO_LIVE_PROGRAMS_LIVEINFO_BACKGROUND_RETURN = 130051;
// 请求参数错误
public static final int REQUEST_PARAMETER_ERROR_OLD_VERSION = 1;
// 用户没有开通对应的平台（朋友、空间、微博...）
public static final int USERS_HAVE_NOT_OPENED_CORRESPONDING_PLATFORMS_FRIENDS_SPACE_MICROBLOG_OLD_VERSION = 2;
// 非法操作，通常是进行了不被授权的操作
public static final int ILLEGAL_OPERATION_USUALLY_UNAUTHORIZED_OPERATION_OLD_VERSION = 1000;
// 用户没有登录态。原因可能有：1）用户没有到该平台注册（没有注册QQ空间，朋友，微博等）；2）openkey过期。
public static final int THE_USER_HAS_NO_LOGIN_STATUS_THE_REASONS_MAY_BE_1_THE_USER_DID_NOT_REGISTER_WITH_THE_PLATFORM_NO_QQ_SPACE_FRIENDS_MICROBLOG_ETC_2_OPENKEY_EXPIRED_OLD_VERSION = 1002;
// 账户被冻结
public static final int ACCOUNT_BLOCKED_OLD_VERSION = 1003;
// 账户余额不足
public static final int INSUFFICIENT_ACCOUNT_BALANCE_OLD_VERSION = 1004;
// 用户没有开通腾讯朋友
public static final int USERS_DON_T_HAVE_TENCENT_FRIENDS_OLD_VERSION = 1005;
// 用户没有开通QQ空间
public static final int THE_USER_HAS_NOT_OPENED_QQ_SPACE_OLD_VERSION = 1006;
// cdkey不存在
public static final int CDKEY_DOES_NOT_EXIST_OLD_VERSION = 1100;
// 用户和cdkey不存在绑定关系，或礼品赠送完毕
public static final int THERE_IS_NO_BINDING_RELATIONSHIP_BETWEEN_THE_USER_AND_CDKEY_OR_THE_GIFT_HAS_BEEN_GIVEN_OLD_VERSION = 1101;
// 参加活动受限
public static final int LIMITED_PARTICIPATION_OLD_VERSION = 1102;
// 多区选服页面登录验证失败，原因：用户登录记录不存在，或登录已超时。
public static final int THE_LOGIN_VERIFICATION_OF_THE_MULTI_ZONE_SERVICE_SELECTION_PAGE_FAILED_BECAUSE_THE_USER_LOGIN_RECORD_DOES_NOT_EXIST_OR_THE_LOGIN_HAS_TIMED_OUT_OLD_VERSION = 1300;
// 请求参数无效。
public static final int INVALID_REQUEST_PARAMETER_OLD_VERSION = -1;
// 请求中的appid不存在
public static final int APPID_IN_REQUEST_DOES_NOT_EXIST_OLD_VERSION = -2;
// 无API访问权限。
public static final int NO_API_ACCESS_OLD_VERSION = -3;
// IP没有权限。
public static final int IP_DOES_NOT_HAVE_PERMISSION_OLD_VERSION = -4;
// 签名参数sig校验失败。
public static final int SIGNATURE_PARAMETER_SIG_VERIFICATION_FAILED_OLD_VERSION = -5;
// 访问频率超限
public static final int ACCESS_FREQUENCY_OUT_OF_LIMIT_OLD_VERSION = -6;
// 协议不合法
public static final int ILLEGAL_AGREEMENT_OLD_VERSION = -7;
// 请求受限，通常是安全审计没通过
public static final int REQUEST_IS_LIMITED_USUALLY_SECURITY_AUDIT_FAILS_OLD_VERSION = -8;
// API不存在。
public static final int API_DOES_NOT_EXIST_OLD_VERSION = -9;
// 在测试环境中进行OpenAPI调试时，传入的是非调试者QQ号对应的OpenID ，将会返回本返回码
public static final int WHEN_DEBUGGING_OPENAPI_IN_THE_TEST_ENVIRONMENT_THE_OPENID_CORRESPONDING_TO_THE_QQ_NUMBER_OF_THE_NON_DEBUGGER_IS_PASSED_IN_AND_THIS_RETURN_CODE_WILL_BE_RETURNED_OLD_VERSION = -12;
// 系统内部错误
public static final int SYSTEM_INTERNAL_ERROR_OLD_VERSION = -13;
// access_token/vusession无效
public static final int INVALID_ACCESS_TOKEN_VUSESSION_OLD_VERSION = -19;
// 应用调用的OpenAPI未经用户授权。
public static final int THE_OPENAPI_CALLED_BY_THE_APPLICATION_IS_NOT_AUTHORIZED_BY_THE_USER_OLD_VERSION = -20;
// access_token已废除，请重新获取access_token。
public static final int ACCESS_TOKEN_HAS_BEEN_REVOKED_PLEASE_GET_ACCESS_TOKEN_AGAIN_OLD_VERSION = -21;
// openid不合法。
public static final int OPENID_IS_ILLEGAL_OLD_VERSION = -22;
// openkey不合法。
public static final int OPENKEY_IS_ILLEGAL_OLD_VERSION = -23;
// openid或者openkey验证失败。
public static final int OPENID_OR_OPENKEY_VALIDATION_FAILED_OLD_VERSION = -24;
// OpenAPI的系统错误（可重试）
public static final int SYSTEM_ERROR_FOR_OPENAPI_RETRYABLE_OLD_VERSION = -58;
// OpenAPI的系统错误（可重试）
public static final int SYSTEM_ERROR_FOR_OPENAPI_RETRYABLE_OLD_VERSION = -60;
// OpenAPI的系统错误（可重试）
public static final int SYSTEM_ERROR_FOR_OPENAPI_RETRYABLE_OLD_VERSION = -65;
// openid和access_token不匹配
public static final int OPENID_AND_ACCESS_TOKEN_DO_NOT_MATCH_OLD_VERSION = -71;
// 此返回码表示用户修改了QQ密码，导致Access Token失效，需要引导用户重新登陆。
public static final int THIS_RETURN_CODE_INDICATES_THAT_THE_USER_HAS_MODIFIED_THE_QQ_PASSWORD_RESULTING_IN_THE_FAILURE_OF_ACCESS_TOKEN_AND_NEEDS_TO_GUIDE_THE_USER_TO_LOG_IN_AGAIN_OLD_VERSION = -73;
// 请求参数错误
public static final int REQUEST_PARAMETER_ERROR_OLD_VERSION = 201;
// 客厅access_token频率限制
public static final int ACCESS_TOKEN_FREQUENCY_LIMIT_IN_LIVING_ROOM_OLD_VERSION = 202;
// 系统错误
public static final int SYSTEM_ERROR_OLD_VERSION = 203;
// 客厅appid无效
public static final int INVALID_LIVING_ROOM_APPID_OLD_VERSION = 204;
// 客厅appid状态异常
public static final int LIVING_ROOM_APPID_STATUS_IS_ABNORMAL_OLD_VERSION = 205;
// 服务器ip限制
public static final int SERVER_IP_RESTRICTIONS_OLD_VERSION = 206;
// access_token无效
public static final int INVALID_ACCESS_OU_TOKEN_OLD_VERSION = 231;
// 客厅access_token过期
public static final int LIVING_ROOM_ACCESS_OU_TOKEN_EXPIRED_OLD_VERSION = 232;
// 条件错误
public static final int CONDITIONAL_ERROR_OLD_VERSION = 1001;
// 未知错误
public static final int UNKNOWN_ERROR_BUSINESS_SIDE_LOGIC_ERROR = 1000001;
// 无效参数
public static final int INVALID_PARAMETER_BUSINESS_SIDE_LOGIC_ERROR = 1000002;
// 分配空间失败
public static final int FAILED_TO_ALLOCATE_SPACE_BUSINESS_SIDE_LOGIC_ERROR = 1000003;
// 无效tpt文件
public static final int INVALID_TPT_FILE_BUSINESS_SIDE_LOGIC_ERROR = 1000004;
// 无效文件类型
public static final int INVALID_FILE_TYPE_BUSINESS_SIDE_LOGIC_ERROR = 1000005;
// seek文件操作失败
public static final int SEEK_FILE_OPERATION_FAILED_BUSINESS_SIDE_LOGIC_ERROR = 1000006;
// 无效文件数据
public static final int INVALID_FILE_DATA_BUSINESS_SIDE_LOGIC_ERROR = 1000007;
// 套接字信息存在
public static final int SOCKET_INFORMATION_EXISTS_BUSINESS_SIDE_LOGIC_ERROR = 1000008;
// 套接字信息不存在
public static final int SOCKET_INFORMATION_DOES_NOT_EXIST_BUSINESS_SIDE_LOGIC_ERROR = 1000009;
// 从Tpt里面校验P2P下载的数据失败
public static final int FAILED_TO_VERIFY_P2P_DOWNLOAD_DATA_FROM_TPT_BUSINESS_SIDE_LOGIC_ERROR = 1000010;
// 从Tpt里面校验本地缓冲的数据失败
public static final int FAILED_TO_VERIFY_LOCAL_BUFFER_DATA_FROM_TPT_BUSINESS_SIDE_LOGIC_ERROR = 1000011;
// 创建线程失败
public static final int FAILED_TO_CREATE_THREAD_BUSINESS_SIDE_LOGIC_ERROR = 1000012;
// 创建条件变量失败
public static final int FAILED_TO_CREATE_CONDITION_VARIABLE_BUSINESS_SIDE_LOGIC_ERROR = 1000013;
// 删除条件变量失败
public static final int FAILED_TO_DELETE_CONDITION_VARIABLE_BUSINESS_SIDE_LOGIC_ERROR = 1000014;
// 等待条件变量失败
public static final int WAIT_CONDITION_VARIABLE_FAILED_BUSINESS_SIDE_LOGIC_ERROR = 1000015;
// 发送条件变量信号失败
public static final int FAILED_TO_SEND_CONDITIONAL_VARIABLE_SIGNAL_BUSINESS_SIDE_LOGIC_ERROR = 1000016;
// 等待条件变量超时
public static final int TIMEOUT_WAITING_FOR_CONDITION_VARIABLE_BUSINESS_SIDE_LOGIC_ERROR = 1000017;
// 没有找到对应的record
public static final int NO_CORRESPONDING_RECORD_FOUND_BUSINESS_SIDE_LOGIC_ERROR = 1000018;
// 没找到PlayData
public static final int PLAYDATA_NOT_FOUND_BUSINESS_SIDE_LOGIC_ERROR = 1000019;
// 建立播放任务失败
public static final int FAILED_TO_CREATE_PLAYBACK_TASK_BUSINESS_SIDE_LOGIC_ERROR = 1000020;
// blockSize错误
public static final int BLOCKSIZE_ERROR_BUSINESS_SIDE_LOGIC_ERROR = 1000021;
// 没找到对应的storageId
public static final int NO_CORRESPONDING_STORAGEID_FOUND_BUSINESS_SIDE_LOGIC_ERROR = 1000022;
// 建立下载任务失败
public static final int FAILED_TO_CREATE_DOWNLOAD_TASK_BUSINESS_SIDE_LOGIC_ERROR = 1000023;
// 没有找到videoInfo
public static final int NO_VIDEOINFO_FOUND_BUSINESS_SIDE_LOGIC_ERROR = 1000024;
// 创建p2p播放任务失败
public static final int FAILED_TO_CREATE_P2P_PLAYBACK_TASK_BUSINESS_SIDE_LOGIC_ERROR = 1000025;
// 获取activeWindowManager失败
public static final int FAILED_TO_GET_ACTIVEWINDOWMANAGER_BUSINESS_SIDE_LOGIC_ERROR = 1000026;
// 文件大小冲突
public static final int FILE_SIZE_CONFLICT_BUSINESS_SIDE_LOGIC_ERROR = 1000027;
// 播放数据不正确
public static final int INCORRECT_PLAYBACK_DATA_BUSINESS_SIDE_LOGIC_ERROR = 1000028;
// 播放提交数据失败
public static final int FAILED_TO_PLAY_SUBMITTED_DATA_BUSINESS_SIDE_LOGIC_ERROR = 1000029;
// block未下载完成
public static final int BLOCK_NOT_DOWNLOADED_BUSINESS_SIDE_LOGIC_ERROR = 1000030;
// 获取系统时间失败
public static final int FAILED_TO_GET_SYSTEM_TIME_BUSINESS_SIDE_LOGIC_ERROR = 1000031;
// 获取分片号失败
public static final int FAILED_TO_GET_PARTITION_NUMBER_BUSINESS_SIDE_LOGIC_ERROR = 1000032;
// 启动mp4任务失败
public static final int FAILED_TO_START_MP4_TASK_BUSINESS_SIDE_LOGIC_ERROR = 1000033;
// mcs不可用
public static final int MCS_NOT_AVAILABLE_BUSINESS_SIDE_LOGIC_ERROR = 1000034;
// 找不到profile文件
public static final int PROFILE_FILE_NOT_FOUND_BUSINESS_SIDE_LOGIC_ERROR = 1000035;
// 存储路径不存在
public static final int STORAGE_PATH_DOES_NOT_EXIST_BUSINESS_SIDE_LOGIC_ERROR = 1000036;
// 已存在下载任务
public static final int DOWNLOAD_TASK_ALREADY_EXISTS_BUSINESS_SIDE_LOGIC_ERROR = 1000037;
// 没有找到指定的cache
public static final int THE_SPECIFIED_CACHE_WAS_NOT_FOUND_BUSINESS_SIDE_LOGIC_ERROR = 1000038;
// 解密key时，值为空
public static final int WHEN_DECRYPTING_THE_KEY_THE_VALUE_IS_EMPTY_BUSINESS_SIDE_LOGIC_ERROR = 1000039;
// 解密nonce时值为空
public static final int WHEN_DECRYPTING_NONCE_THE_VALUE_IS_NULL_BUSINESS_SIDE_LOGIC_ERROR = 1000040;
// 没有找到Playdata
public static final int PLAYDATA_NOT_FOUND_BUSINESS_SIDE_LOGIC_ERROR = 1000041;
// 开启mp4任务失败
public static final int FAILED_TO_OPEN_MP4_TASK_BUSINESS_SIDE_LOGIC_ERROR = 1000042;
// 获取AWM失败
public static final int FAILED_TO_GET_AWM_BUSINESS_SIDE_LOGIC_ERROR = 1000043;
// 代理URL有误
public static final int WRONG_PROXY_URL_BUSINESS_SIDE_LOGIC_ERROR = 1000044;
// PlayData没有准备好
public static final int PLAYDATA_IS_NOT_READY_BUSINESS_SIDE_LOGIC_ERROR = 1000045;
// 创建下载任务失败
public static final int FAILED_TO_CREATE_DOWNLOAD_TASK_BUSINESS_SIDE_LOGIC_ERROR = 1000046;
// 找不到记录
public static final int RECORD_NOT_FOUND_BUSINESS_SIDE_LOGIC_ERROR = 1000047;
// 数据不足
public static final int INSUFFICIENT_DATA_BUSINESS_SIDE_LOGIC_ERROR = 1000048;
// 发送给播放器失败
public static final int SEND_TO_PLAYER_FAILED_BUSINESS_SIDE_LOGIC_ERROR = 1000049;
// 校验文件失败
public static final int FAILED_TO_VERIFY_FILE_BUSINESS_SIDE_LOGIC_ERROR = 1000050;
// 创建任务失败
public static final int FAILED_TO_CREATE_TASK_BUSINESS_SIDE_LOGIC_ERROR = 1000051;
// 开始任务失败
public static final int START_TASK_FAILED_BUSINESS_SIDE_LOGIC_ERROR = 1000052;
// 任务不存在
public static final int TASK_DOES_NOT_EXIST_BUSINESS_SIDE_LOGIC_ERROR = 1000053;
// 后台返回加密视频，但是加密key为空
public static final int THE_BACKGROUND_RETURNS_ENCRYPTED_VIDEO_BUT_THE_ENCRYPTION_KEY_IS_EMPTY_BUSINESS_SIDE_LOGIC_ERROR = 1000054;
// 创建HLS任务失败
public static final int FAILED_TO_CREATE_HLS_TASK_BUSINESS_SIDE_LOGIC_ERROR = 1000055;
// 开始HLS任务失败
public static final int FAILED_TO_START_HLS_TASK_BUSINESS_SIDE_LOGIC_ERROR = 1000056;
// 请求的下载类型和返回的下载类型不一致
public static final int THE_REQUESTED_DOWNLOAD_TYPE_IS_INCONSISTENT_WITH_THE_RETURNED_DOWNLOAD_TYPE_BUSINESS_SIDE_LOGIC_ERROR = 1000057;
// 解密key时值为空
public static final int THE_VALUE_IS_EMPTY_WHEN_DECRYPTING_THE_KEY_BUSINESS_SIDE_LOGIC_ERROR = 1000058;
// 解密nonce时值为空
public static final int WHEN_DECRYPTING_NONCE_THE_VALUE_IS_NULL_BUSINESS_SIDE_LOGIC_ERROR = 1000059;
// 创建下载任务失败，原因为record为空
public static final int FAILED_TO_CREATE_DOWNLOAD_TASK_BECAUSE_RECORD_IS_EMPTY_BUSINESS_SIDE_LOGIC_ERROR = 1000060;
// 创建下载任务失败，原因为初始化失败
public static final int FAILED_TO_CREATE_DOWNLOAD_TASK_BECAUSE_INITIALIZATION_FAILED_BUSINESS_SIDE_LOGIC_ERROR = 1000061;
// 创建下载任务失败，openCache失败
public static final int FAILED_TO_CREATE_DOWNLOAD_TASK_OPENCACHE_FAILED_BUSINESS_SIDE_LOGIC_ERROR_MIN = 1000062;
public static final int FAILED_TO_CREATE_DOWNLOAD_TASK_OPENCACHE_FAILED_BUSINESS_SIDE_LOGIC_ERROR_MAX = 1000072;
// 创建下载任务失败，获取配置信息失败（系统错误码）
public static final int FAILED_TO_CREATE_DOWNLOAD_TASK_FAILED_TO_GET_CONFIGURATION_INFORMATION_SYSTEM_ERROR_CODE_BUSINESS_SIDE_LOGIC_ERROR_MIN = 1000073;
public static final int FAILED_TO_CREATE_DOWNLOAD_TASK_FAILED_TO_GET_CONFIGURATION_INFORMATION_SYSTEM_ERROR_CODE_BUSINESS_SIDE_LOGIC_ERROR_MAX = 1000272;
// 创建套接字失败
public static final int FAILED_TO_CREATE_SOCKET_NETWORK_OPERATION_ERROR = 1400001;
// 绑定本地端口失败
public static final int FAILED_TO_BIND_LOCAL_PORT_NETWORK_OPERATION_ERROR = 1400002;
// 套接字监听失败
public static final int SOCKET_LISTENING_FAILED_NETWORK_OPERATION_ERROR = 1400003;
// 获取套接字选项失败
public static final int FAILED_TO_GET_SOCKET_OPTIONS_NETWORK_OPERATION_ERROR = 1400004;
// 设置套接字选项失败
public static final int FAILED_TO_SET_SOCKET_OPTIONS_NETWORK_OPERATION_ERROR = 1400005;
// 转换ip地址失败
public static final int FAILED_TO_TRANSLATE_IP_ADDRESS_NETWORK_OPERATION_ERROR = 1400006;
// 连接服务器失败
public static final int FAILED_TO_CONNECT_TO_SERVER_NETWORK_OPERATION_ERROR = 1400007;
// 发送数据失败
public static final int FAILED_TO_SEND_DATA_NETWORK_OPERATION_ERROR = 1400008;
// 关闭套接字失败
public static final int FAIL_IN_CLOSE_SOCKET_NETWORK_OPERATION_ERROR = 1400009;
// select函数失败
public static final int SELECT_FUNCTION_FAILED_NETWORK_OPERATION_ERROR = 1400010;
// 接受新的用户失败
public static final int FAILED_TO_ACCEPT_NEW_USER_NETWORK_OPERATION_ERROR = 1400011;
// 接受数据失败
public static final int FAILED_TO_ACCEPT_DATA_NETWORK_OPERATION_ERROR = 1400012;
// 加入多播组失败
public static final int FAILED_TO_JOIN_MULTICAST_GROUP_NETWORK_OPERATION_ERROR = 1400013;
// 设置多播不反馈本地失败
public static final int FAILED_TO_SET_MULTICAST_NO_FEEDBACK_LOCAL_NETWORK_OPERATION_ERROR = 1400014;
// 退出多播组失败
public static final int FAILED_TO_EXIT_MULTICAST_GROUP_NETWORK_OPERATION_ERROR = 1400015;
// 无效套接字
public static final int INVALID_SOCKET_NETWORK_OPERATION_ERROR = 1400016;
// http返回错误
public static final int HTTP_RETURNED_ERROR_NETWORK_OPERATION_ERROR = 1400017;
// http服务不可用
public static final int HTTP_SERVICE_NOT_AVAILABLE_NETWORK_OPERATION_ERROR = 1400018;
// 用户网络不可用
public static final int USER_NETWORK_NOT_AVAILABLE_NETWORK_OPERATION_ERROR = 1400019;
// 用户网络被劫持
public static final int USER_NETWORK_HIJACKED_NETWORK_OPERATION_ERROR = 1400020;
// 下载文件md5值连续检验失败多次
public static final int DOWNLOAD_FILE_MD5_VALUE_CONTINUOUS_VERIFICATION_FAILED_MULTIPLE_TIMES_NETWORK_OPERATION_ERROR = 1400021;
// 离线下载请求drm超时
public static final int OFFLINE_DOWNLOAD_REQUEST_DRM_TIMEOUT_NETWORK_OPERATION_ERROR = 1400022;
// getLicense超时
public static final int GETLICENSE_TIMEOUT_NETWORK_OPERATION_ERROR = 1400023;
// http服务不存在
public static final int HTTP_SERVICE_DOES_NOT_EXIST_NETWORK_OPERATION_ERROR = 1400024;
// cdn连接有错误
public static final int CDN_CONNECTION_ERROR_NETWORK_OPERATION_ERROR = 1400025;
// 下载url为null
public static final int DOWNLOAD_URL_IS_NULL_NETWORK_OPERATION_ERROR = 1403001;
// DNS解析错误
public static final int DNS_RESOLUTION_ERROR_NETWORK_OPERATION_ERROR = 1403002;
// 创建socket错误
public static final int ERROR_CREATING_SOCKET_NETWORK_OPERATION_ERROR = 1403003;
// 连接出错
public static final int LINK_ERROR_NETWORK_OPERATION_ERROR = 1403004;
// 发送错误
public static final int SEND_ERROR_NETWORK_OPERATION_ERROR = 1403005;
// 接受出错
public static final int ACCEPT_ERROR_NETWORK_OPERATION_ERROR = 1403006;
// poll select超时
public static final int POLL_SELECT_TIMEOUT_NETWORK_OPERATION_ERROR = 1403007;
// 重定向IP出错
public static final int ERROR_REDIRECTING_IP_NETWORK_OPERATION_ERROR = 1403008;
// 重定向次数过多出错
public static final int TOO_MANY_REDIRECTS_ERROR_NETWORK_OPERATION_ERROR = 1403009;
// http状态码错误
public static final int HTTP_STATUS_CODE_ERROR_NETWORK_OPERATION_ERROR = 1403010;
// http解析错误
public static final int HTTP_PARSING_ERROR_NETWORK_OPERATION_ERROR = 1403011;
// 返回的xml解析出错
public static final int ERROR_IN_XML_PARSING_RETURNED_NETWORK_OPERATION_ERROR = 1403012;
// 返回的内容出错
public static final int ERROR_IN_RETURNED_CONTENT_NETWORK_OPERATION_ERROR = 1403013;
// http超时（3s）
public static final int HTTP_TIMEOUT_3S_NETWORK_OPERATION_ERROR = 1403014;
// Send返回EAGAIN
public static final int SEND_RETURNS_EAGAIN_NETWORK_OPERATION_ERROR = 1403015;
// 对于连接的socket,getsockopt失败
public static final int GETSOCKOPT_FAILED_FOR_THE_CONNECTED_SOCKET_NETWORK_OPERATION_ERROR = 1403016;
// 对于连接的socket,getsockopt成功，但是返回了ERROR
public static final int GETSOCKOPT_SUCCEEDED_FOR_THE_CONNECTED_SOCKET_BUT_RETURNED_ERROR_NETWORK_OPERATION_ERROR = 1403017;
// hls http参数不合法
public static final int ILLEGAL_HLS_HTTP_PARAMETER_NETWORK_OPERATION_ERROR = 1410001;
// hls url不合法
public static final int ILLEGAL_HLS_URL_NETWORK_OPERATION_ERROR = 1410002;
// hls dns解析失败
public static final int HLS_DNS_PARSING_FAILED_NETWORK_OPERATION_ERROR = 1410003;
// hls 创建socket失败
public static final int HLS_FAILED_TO_CREATE_SOCKET_NETWORK_OPERATION_ERROR = 1410004;
// hls 连接失败
public static final int HLS_CONNECTION_FAILED_NETWORK_OPERATION_ERROR = 1410005;
// hls 连接超时
public static final int HLS_CONNECTION_TIMEOUT_NETWORK_OPERATION_ERROR = 1410006;
// hls 发送超时
public static final int HLS_SEND_TIMEOUT_NETWORK_OPERATION_ERROR = 1410007;
// hls 申请内存失败
public static final int HLS_FAILED_TO_APPLY_FOR_MEMORY_NETWORK_OPERATION_ERROR = 1410008;
// hls 接受失败
public static final int HLS_ACCEPT_FAILED_NETWORK_OPERATION_ERROR = 1410009;
// hls 接受超时
public static final int HLS_ACCEPT_TIMEOUT_NETWORK_OPERATION_ERROR = 1410010;
// hls buffer不足
public static final int INSUFFICIENT_HLS_BUFFER_NETWORK_OPERATION_ERROR = 1410011;
// hls http头溢出
public static final int HLS_HTTP_HEADER_OVERFLOW_NETWORK_OPERATION_ERROR = 1410012;
// hls http返回错误码检测非法
public static final int HLS_HTTP_RETURN_ERROR_CODE_DETECTION_ILLEGAL_NETWORK_OPERATION_ERROR = 1410013;
// hls http返回文件大小非法
public static final int ILLEGAL_FILE_SIZE_RETURNED_BY_HLS_HTTP_NETWORK_OPERATION_ERROR = 1410014;
// hls http ContentLength非法
public static final int ILLEGAL_HLS_HTTP_CONTENTLENGTH_NETWORK_OPERATION_ERROR = 1410015;
// hls http从定向非法
public static final int HLS_HTTP_FROM_DIRECTED_ILLEGAL_NETWORK_OPERATION_ERROR = 1410016;
// hls 返回http错误码
public static final int HLS_RETURNS_HTTP_ERROR_CODE_NETWORK_OPERATION_ERROR = 1410017;
// hls 接受溢出
public static final int HLS_ACCEPT_OVERFLOW_NETWORK_OPERATION_ERROR = 1410018;
// hls 服务器异常关闭
public static final int HLS_SERVER_SHUT_DOWN_ABNORMALLY_NETWORK_OPERATION_ERROR = 1410019;
// hls socket错误
public static final int HLS_SOCKET_ERROR_NETWORK_OPERATION_ERROR = 1410020;
// hls 重试超过限制
public static final int HLS_RETRY_EXCEEDED_LIMIT_NETWORK_OPERATION_ERROR = 1410021;
// hls 未知错误
public static final int HLS_UNKNOWN_ERROR_NETWORK_OPERATION_ERROR = 1410022;
// 锁失败
public static final int LOCK_FAILURE_NETWORK_OPERATION_ERROR = 1410023;
// hls 连接中
public static final int IN_HLS_CONNECTION_NETWORK_OPERATION_ERROR = 1410024;
// hls socket正忙
public static final int HLS_SOCKET_IS_BUSY_NETWORK_OPERATION_ERROR = 1410025;
// hls 下载ts时发生302跳转
public static final int 302_JUMP_WHEN_HLS_DOWNLOADS_TS_NETWORK_OPERATION_ERROR = 1410026;
// hls 302跳转到相同的URL
public static final int HLS_302_JUMPS_TO_THE_SAME_URL_NETWORK_OPERATION_ERROR = 1410027;
// hls 返回的ContentType有错
public static final int CONTENT_TYPE_RETURNED_BY_HLS_IS_WRONG_NETWORK_OPERATION_ERROR = 1410028;
// hls cdn返回的文件大小发生变化
public static final int FILE_SIZE_RETURNED_BY_HLS_CDN_CHANGES_NETWORK_OPERATION_ERROR = 1410029;
// hls 302跳转次数过多
public static final int TOO_MANY_JUMPS_IN_HLS_302_NETWORK_OPERATION_ERROR = 1410030;
// 打开文件失败
public static final int FAIL_TO_OPEN_FILE_DOCUMENT_OPERATION_RELATED = 1500001;
// 获取文件失败
public static final int FAILED_TO_GET_FILE_DOCUMENT_OPERATION_RELATED = 1500002;
// 写文件失败
public static final int FAILED_TO_WRITE_FILE_DOCUMENT_OPERATION_RELATED = 1500003;
// 获取文件大小失败
public static final int FAILED_TO_GET_FILE_SIZE_DOCUMENT_OPERATION_RELATED = 1500004;
// 磁盘空间不足
public static final int INSUFFICIENT_DISK_SPACE_DOCUMENT_OPERATION_RELATED = 1500005;
// 文件没找到
public static final int FILE_WAS_NOT_FOUND_DOCUMENT_OPERATION_RELATED = 1500006;
// vfs为空
public static final int VFS_IS_EMPTY_DOCUMENT_OPERATION_RELATED = 1500007;
// 没有这个路径
public static final int THERE_IS_NO_SUCH_PATH_DOCUMENT_OPERATION_RELATED = 1500008;
// 找不到cache
public static final int CACHE_NOT_FOUND_DOCUMENT_OPERATION_RELATED = 1500009;
// 读cache失败
public static final int FAILED_TO_READ_CACHE_DOCUMENT_OPERATION_RELATED = 1500010;
// 写cache失败
public static final int WRITE_CACHE_FAILED_DOCUMENT_OPERATION_RELATED = 1500011;
// 离线文件不存在
public static final int OFFLINE_FILE_DOES_NOT_EXIST_DOCUMENT_OPERATION_RELATED = 1500012;
// 磁盘空间不足
public static final int INSUFFICIENT_DISK_SPACE_DOCUMENT_OPERATION_RELATED = 1500013;
// 下载文件重命名失败
public static final int DOWNLOAD_FILE_RENAME_FAILED_DOCUMENT_OPERATION_RELATED = 1500014;
// 写文件长度错误
public static final int WRITE_FILE_LENGTH_ERROR_DOCUMENT_OPERATION_RELATED = 1500015;
// 切换设置的目录为空
public static final int THE_DIRECTORY_FOR_TOGGLE_SETTINGS_IS_EMPTY_DOCUMENT_OPERATION_RELATED = 1500016;
// 切换设置的目录创建目录为空
public static final int THE_DIRECTORY_CREATION_DIRECTORY_FOR_TOGGLE_SETTINGS_IS_EMPTY_DOCUMENT_OPERATION_RELATED = 1500017;
// 读写文件系统错误码
public static final int READ_WRITE_FILE_SYSTEM_ERROR_CODE_DOCUMENT_OPERATION_RELATED_MIN = 1500018;
public static final int READ_WRITE_FILE_SYSTEM_ERROR_CODE_DOCUMENT_OPERATION_RELATED_MAX = 1500218;
// 系统基本错误码
public static final int SYSTEM_BASIC_ERROR_CODE_DOCUMENT_OPERATION_RELATED_MIN = 1510001;
public static final int SYSTEM_BASIC_ERROR_CODE_DOCUMENT_OPERATION_RELATED_MAX = 1510201;
// vfs 打开失败
public static final int VFS_OPEN_FAILED_DOCUMENT_OPERATION_RELATED = 1510202;
// vfs 无效参数
public static final int VFS_INVALID_PARAMETER_DOCUMENT_OPERATION_RELATED = 1510203;
// offset 非法
public static final int ILLEGAL_OFFSET_DOCUMENT_OPERATION_RELATED = 1510204;
// 本地缓冲没数据
public static final int NO_DATA_IN_LOCAL_BUFFER_DOCUMENT_OPERATION_RELATED = 1510205;
// 更新record失败
public static final int FAILED_TO_UPDATE_RECORD_DB_RELATED_ERROR = 1600001;
// 更新vinfo失败
public static final int FAILED_TO_UPDATE_VINFO_DB_RELATED_ERROR = 1600002;
// 记录删除db失败
public static final int RECORD_DELETE_DB_FAILED_DB_RELATED_ERROR = 1600003;
// 添加记录失败
public static final int FAILED_TO_ADD_RECORD_DB_RELATED_ERROR = 1600004;
// 升级时转换vfs失败
public static final int FAILED_TO_CONVERT_VFS_ON_UPGRADE_DB_RELATED_ERROR = 1600005;
// 升级时更新vinfo信息失败
public static final int FAILED_TO_UPDATE_VINFO_INFORMATION_DURING_UPGRADE_DB_RELATED_ERROR = 1600006;
// cdn返回的相关的http错误码
public static final int RELATED_HTTP_ERROR_CODES_RETURNED_BY_CDN_CDN_RELATED_ERRORS = 1700001;
// hls 302
public static final int HLS_302_CDN_RELATED_ERRORS = 1710302;
// hls 403
public static final int HLS_403_CDN_RELATED_ERRORS = 1710403;
// hls 404
public static final int HLS_404_CDN_RELATED_ERRORS = 1710404;
// hls 416
public static final int HLS_416_CDN_RELATED_ERRORS = 1710416;
